group:
  repos: |
    ssi-dk/diseasystore
    ssi-dk/diseasy
  files:
    - .github/workflows
    - .github/templates
    - .github/sync.yaml
    - .github/PULL_REQUEST_TEMPLATE.md

    - .lintr

    - inst/WORDLIST

    - R/0_linters.R
    - tests/testthat/test-0_linters.R

    - R/0_R6_utils.R
    - tests/testthat/test-0_R6_utils.R

    - R/0_documentation.R
    - tests/testthat/test-0_documentation.R

    - tests/testthat/test-0_rd_files.R


ssi-dk/diseasystore:
  - source: .github/templates/_pkgdown.yml
    dest: _pkgdown.yml
    template:
      repo:
        name: "diseasystore"

  - source: .github/templates/bug_report.md
    dest: .github/ISSUE_TEMPLATE/bug_report.md
    template:
      repo:
        name: "diseasystore"

  - source: .github/README_body.Rmd
    dest: README.Rmd
    template:
      repo:
        name: "diseasystore"


ssi-dk/diseasy:
  - source: .github/templates/_pkgdown.yml
    dest: _pkgdown.yml
    template:
      repo:
        name: "diseasy"

  - source: .github/templates/bug_report.md
    dest: .github/ISSUE_TEMPLATE/bug_report.md
    template:
      repo:
        name: "diseasy"

  - source: .github/README_body.Rmd
    dest: README.Rmd
    template:
      repo:
        name: "diseasy"
