group:
  repos: |
    ssi-dk/diseasystore:
    ssi-dk/diseasy
  files:
    - .github/workflows
    - .github/sync.yaml

    - .lintr
    - _pkgdown.yml

    - inst/WORDLIST

    - R/0_linters.R
    - tests/testthat/test-0_linters.R

    - R/0_R6_utils.R
    - tests/testthat/test-0_R6_utils.R

    - R/0_documentation.R
    - tests/testthat/test-0_documentation.R

    - tests/testthat/test-0_rd_files.R


