group:
  - repos: |
      ssi-dk/diseasystore
      ssi-dk/diseasy
    files:
      - .github/sync.yaml

      - inst/WORDLIST

      - R/0_R6_utils.R
      - tests/testthat/test-0_R6_utils.R

      - R/0_documentation.R
      - tests/testthat/test-0_documentation.R

      - R/0_miscellaneous.R

  - repos: |
      ssi-dk/SCDB
    files:
      - R/0_miscellaneous.R
