# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
on:
  push:
    inputs:
      cache_version:
        type: string
        default: '1'

jobs:
  R-CMD-check:
    name: "🔎 Check: SCDB v0.3, ${{ matrix.config.os }} (${{ matrix.config.r }})"
    runs-on: ${{ matrix.config.os }}-latest

    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: macos,    r: 'release'}
          - {os: windows,  r: 'release'}
          - {os: ubuntu,   r: 'release'}
          - {os: ubuntu,   r: 'oldrel-1'}

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes
      BACKEND: SQLite
      BACKEND_DRV: RSQLite::SQLite
      BACKEND_ARGS: 'list(dbname = file.path(tempdir(), "SQLite.SQLite"))'

    steps:
      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.config.r }}
          http-user-agent: ${{ matrix.config.http-user-agent }}
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          cache-version: '1'
          extra-packages: any::rcmdcheck
          needs: check

      - uses: r-lib/actions/check-r-package@v2
        with:
          upload-snapshots: true
          args: c("--no-manual", "--as-cran", "--no-tests")

  R-CMD-check-hard-old:
    runs-on: ubuntu-latest
    name: "🔎 Check: SCDB v0.3, ubuntu (release, no dependencies)"

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes
      BACKEND: SQLite
      BACKEND_DRV: RSQLite::SQLite
      BACKEND_ARGS: 'list(dbname = file.path(tempdir(), "SQLite.SQLite"))'

    steps:
      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          dependencies: '"hard"'
          cache: false
          extra-packages: |
            any::rcmdcheck
            any::testthat
            any::knitr
            any::rmarkdown
          needs: check

      - uses: r-lib/actions/check-r-package@v2
        with:
          upload-snapshots: true


  R-CMD-check-devel-old:
    runs-on: ubuntu-latest
    name: "🔎 Check: SCDB v0.3, ubuntu (r-devel)"

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes
      BACKEND: SQLite
      BACKEND_DRV: RSQLite::SQLite
      BACKEND_ARGS: 'list(dbname = file.path(tempdir(), "SQLite.SQLite"))'

    steps:
      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          cache-version: '1'
          extra-packages: any::rcmdcheck
          needs: check

      - uses: r-lib/actions/check-r-package@v2
        with:
          upload-snapshots: true


  R-CMD-check-new:
    name: "🔎 Check: SCDB v0.4, ${{ matrix.config.os }} (${{ matrix.config.r }})"
    runs-on: ${{ matrix.config.os }}-latest

    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: macos,    r: 'release'}
          - {os: windows,  r: 'release'}
          - {os: ubuntu,   r: 'release'}
          - {os: ubuntu,   r: 'oldrel-1'}

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes
      BACKEND: SQLite
      BACKEND_DRV: RSQLite::SQLite
      BACKEND_ARGS: 'list(dbname = file.path(tempdir(), "SQLite.SQLite"))'

    steps:
      - uses: actions/checkout@v4

      - name: Set SCDB version to v0.4
        run: |
          perl -pi -e 's/SCDB \(>= 0.3.0\)/SCDB \(>= 0.4.0\)/g' DESCRIPTION

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.config.r }}
          http-user-agent: ${{ matrix.config.http-user-agent }}
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          cache-version: '0'
          extra-packages: any::rcmdcheck, github::ssi-dk/SCDB@rc-v0.4
          needs: check

      - uses: r-lib/actions/check-r-package@v2
        with:
          upload-snapshots: true
          args: c("--no-manual", "--as-cran", "--no-tests")

  R-CMD-check-hard-new:
    runs-on: ubuntu-latest
    name: "🔎 Check: SCDB v0.4, ubuntu (release, no dependencies)"

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes
      BACKEND: SQLite
      BACKEND_DRV: RSQLite::SQLite
      BACKEND_ARGS: 'list(dbname = file.path(tempdir(), "SQLite.SQLite"))'

    steps:
      - uses: actions/checkout@v4

      - name: Set SCDB version to v0.4
        run: |
          perl -pi -e 's/SCDB \(>= 0.3.0\)/SCDB \(>= 0.4.0\)/g' DESCRIPTION

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          dependencies: '"hard"'
          cache: false
          extra-packages: |
            any::rcmdcheck
            any::testthat
            any::knitr
            any::rmarkdown
            github::ssi-dk/SCDB@rc-v0.4
          needs: check

      - uses: r-lib/actions/check-r-package@v2
        with:
          upload-snapshots: true


  R-CMD-check-devel-new:
    runs-on: ubuntu-latest
    name: "🔎 Check: SCDB v0.4, ubuntu (r-devel)"

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes
      BACKEND: SQLite
      BACKEND_DRV: RSQLite::SQLite
      BACKEND_ARGS: 'list(dbname = file.path(tempdir(), "SQLite.SQLite"))'

    steps:
      - uses: actions/checkout@v4

      - name: Set SCDB version to v0.4
        run: |
          perl -pi -e 's/SCDB \(>= 0.3.0\)/SCDB \(>= 0.4.0\)/g' DESCRIPTION

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          cache-version: '0'
          extra-packages: any::rcmdcheck, github::ssi-dk/SCDB@rc-v0.4
          needs: check

      - uses: r-lib/actions/check-r-package@v2
        with:
          upload-snapshots: true
